import { ActivitiesProps } from "@/app/commons/types/types";

export const mockActivities: ActivitiesProps[] = [
    // リムジン
    {
        id: 1,
        subcategory: "リムジン",
        image: "",
        provider_name: "OneRide Limousine",
        time_zone: "夜",
        solo_level: "上級",
        likes_count: 10,
        favorites_count: 20,
    },
    {
        id: 2,
        subcategory: "リムジン",
        image: "",
        provider_name: "スターリムジン",
        time_zone: "夜",
        solo_level: "上級",
        likes_count: 30,
        favorites_count: 25,
    },
    {
        id: 3,
        subcategory: "リムジン",
        image: "",
        provider_name: "ラグジュアリーライド",
        time_zone: "昼",
        solo_level: "中級",
        likes_count: 15,
        favorites_count: 18,
    },
    {
        id: 4,
        subcategory: "リムジン",
        image: "",
        provider_name: "エレガントリモ",
        time_zone: "夜",
        solo_level: "初級",
        likes_count: 8,
        favorites_count: 12,
    },
    {
        id: 5,
        subcategory: "リムジン",
        image: "",
        provider_name: "プレミアムカー",
        time_zone: "朝",
        solo_level: "中級",
        likes_count: 20,
        favorites_count: 30,
    },

    // 気球
    {
        id: 6,
        subcategory: "気球",
        image: "",
        provider_name: "スマイルバルーン",
        time_zone: "朝",
        solo_level: "上級",
        likes_count: 20,
        favorites_count: 55,
    },
    {
        id: 7,
        subcategory: "気球",
        image: "",
        provider_name: "スカイアドベンチャー",
        time_zone: "夕方",
        solo_level: "中級",
        likes_count: 18,
        favorites_count: 40,
    },
    {
        id: 8,
        subcategory: "気球",
        image: "",
        provider_name: "フライングドリームス",
        time_zone: "朝",
        solo_level: "初級",
        likes_count: 12,
        favorites_count: 30,
    },
    {
        id: 9,
        subcategory: "気球",
        image: "",
        provider_name: "エアリアルビュー",
        time_zone: "夕方",
        solo_level: "上級",
        likes_count: 25,
        favorites_count: 60,
    },

    // ヘリクルーズ
    {
        id: 10,
        subcategory: "ヘリクルーズ",
        image: "",
        provider_name: "AIROS Skyview",
        time_zone: "夜",
        solo_level: "上級",
        likes_count: 15,
        favorites_count: 10,
    },
    {
        id: 11,
        subcategory: "ヘリクルーズ",
        image: "",
        provider_name: "シティヘリツアー",
        time_zone: "昼",
        solo_level: "中級",
        likes_count: 20,
        favorites_count: 15,
    },
    {
        id: 12,
        subcategory: "ヘリクルーズ",
        image: "",
        provider_name: "スカイハイアドベンチャー",
        time_zone: "夕方",
        solo_level: "上級",
        likes_count: 25,
        favorites_count: 20,
    },
    {
        id: 13,
        subcategory: "ヘリクルーズ",
        image: "",
        provider_name: "エアリアルエクスペリエンス",
        time_zone: "朝",
        solo_level: "初級",
        likes_count: 10,
        favorites_count: 8,
    },
    {
        id: 14,
        subcategory: "ヘリクルーズ",
        image: "",
        provider_name: "パノラマフライト",
        time_zone: "夜",
        solo_level: "中級",
        likes_count: 18,
        favorites_count: 12,
    },

    // シティホテル
    {
        id: 15,
        subcategory: "シティホテル",
        image: "",
        provider_name: "ホテルニューオータニ",
        time_zone: "夜",
        solo_level: "上級",
        likes_count: 30,
        favorites_count: 40,
    },
    {
        id: 16,
        subcategory: "シティホテル",
        image: "",
        provider_name: "パークハイアット東京",
        time_zone: "昼",
        solo_level: "上級",
        likes_count: 35,
        favorites_count: 45,
    },
    {
        id: 17,
        subcategory: "シティホテル",
        image: "",
        provider_name: "マンダリンオリエンタル東京",
        time_zone: "夜",
        solo_level: "上級",
        likes_count: 40,
        favorites_count: 50,
    },
    {
        id: 18,
        subcategory: "シティホテル",
        image: "",
        provider_name: "ザ・リッツ・カールトン東京",
        time_zone: "昼",
        solo_level: "上級",
        likes_count: 45,
        favorites_count: 55,
    },
    {
        id: 19,
        subcategory: "シティホテル",
        image: "",
        provider_name: "アマン東京",
        time_zone: "夜",
        solo_level: "上級",
        likes_count: 50,
        favorites_count: 60,
    },
];