import { ActivitiesProps } from "@/app/commons/types/types";

export const mockActivities: ActivitiesProps[] = [
    // リムジン
    {
        id: 1,
        subcategory: "リムジン",
        image: "limousine.jpg",
        provider_name: "OneRide Limousine",
        time_zone: "夜",
        solo_level: "上級",
        likes_count: 38,
        favorites_count: 27,
    },
    {
        id: 2,
        subcategory: "リムジン",
        image: "limousine02.jpg",
        provider_name: "スターリムジン",
        time_zone: "夜",
        solo_level: "上級",
        likes_count: 30,
        favorites_count: 25,
    },
    {
        id: 3,
        subcategory: "リムジン",
        image: "limousine03.jpg",
        provider_name: "ラグジュアリーライド",
        time_zone: "昼",
        solo_level: "中級",
        likes_count: 15,
        favorites_count: 18,
    },
    {
        id: 4,
        subcategory: "リムジン",
        image: "limousine04.jpg",
        provider_name: "エレガントリモ",
        time_zone: "夜",
        solo_level: "初級",
        likes_count: 8,
        favorites_count: 12,
    },
    {
        id: 5,
        subcategory: "リムジン",
        image: "limousine05.jpg",
        provider_name: "プレミアムカー",
        time_zone: "朝",
        solo_level: "中級",
        likes_count: 20,
        favorites_count: 30,
    },
    {
        id: 6,
        subcategory: "リムジン",
        image: "limousine06.jpg",
        provider_name: "チャリオット",
        time_zone: "夕方",
        solo_level: "上級",
        likes_count: 22,
        favorites_count: 35,
    },

    // 気球
    {
        id: 7,
        subcategory: "気球",
        image: "balloon.jpg",
        provider_name: "スマイルバルーン",
        time_zone: "朝",
        solo_level: "上級",
        likes_count: 20,
        favorites_count: 55,
    },
    {
        id: 8,
        subcategory: "気球",
        image: "balloon02.jpg",
        provider_name: "スカイアドベンチャー",
        time_zone: "夕方",
        solo_level: "中級",
        likes_count: 18,
        favorites_count: 40,
    },
    {
        id: 9,
        subcategory: "気球",
        image: "balloon03.jpg",
        provider_name: "フライングドリームス",
        time_zone: "朝",
        solo_level: "初級",
        likes_count: 12,
        favorites_count: 30,
    },
    {
        id: 10,
        subcategory: "気球",
        image: "balloon04.jpg",
        provider_name: "エアリアルビュー",
        time_zone: "夕方",
        solo_level: "上級",
        likes_count: 25,
        favorites_count: 60,
    },
    {
        id: 11,
        subcategory: "気球",
        image: "balloon05.jpg",
        provider_name: "サンライズバルーン",
        time_zone: "朝",
        solo_level: "中級",
        likes_count: 23,
        favorites_count: 50,
    },
    {
        id: 12,
        subcategory: "気球",
        image: "balloon06.jpg",
        provider_name: "スカイハイ",
        time_zone: "夜",
        solo_level: "上級",
        likes_count: 28,
        favorites_count: 65,
    },

    // ヘリクルーズ
    {
        id: 13,
        subcategory: "ヘリクルーズ",
        image: "helicopter.jpg",
        provider_name: "AIROS Skyview",
        time_zone: "夜",
        solo_level: "上級",
        likes_count: 15,
        favorites_count: 10,
    },
    {
        id: 14,
        subcategory: "ヘリクルーズ",
        image: "helicopter02.jpg",
        provider_name: "シティヘリツアー",
        time_zone: "昼",
        solo_level: "中級",
        likes_count: 20,
        favorites_count: 15,
    },
    {
        id: 15,
        subcategory: "ヘリクルーズ",
        image: "helicopter03.jpg",
        provider_name: "スカイハイ",
        time_zone: "夕方",
        solo_level: "上級",
        likes_count: 25,
        favorites_count: 20,
    },
    {
        id: 16,
        subcategory: "ヘリクルーズ",
        image: "helicopter04.jpg",
        provider_name: "エアリアル",
        time_zone: "朝",
        solo_level: "初級",
        likes_count: 10,
        favorites_count: 8,
    },
    {
        id: 17,
        subcategory: "ヘリクルーズ",
        image: "helicopter05.jpg",
        provider_name: "パノラマフライト",
        time_zone: "夜",
        solo_level: "中級",
        likes_count: 18,
        favorites_count: 12,
    },
    {
        id: 18,
        subcategory: "ヘリクルーズ",
        image: "helicopter06.jpg",
        provider_name: "スカイライン",
        time_zone: "昼",
        solo_level: "上級",
        likes_count: 22,
        favorites_count: 17,
    },

    // シティホテル
    {
        id: 19,
        subcategory: "シティホテル",
        image: "hotel.jpg",
        provider_name: "ホテルニューオータニ",
        time_zone: "夜",
        solo_level: "上級",
        likes_count: 30,
        favorites_count: 40,
    },
    {
        id: 20,
        subcategory: "シティホテル",
        image: "hotel02.jpg",
        provider_name: "パークハイアット東京",
        time_zone: "昼",
        solo_level: "上級",
        likes_count: 35,
        favorites_count: 45,
    },
    {
        id: 21,
        subcategory: "シティホテル",
        image: "hotel03.jpg",
        provider_name: "オリエンタル東京",
        time_zone: "夜",
        solo_level: "上級",
        likes_count: 40,
        favorites_count: 50,
    },
    {
        id: 22,
        subcategory: "シティホテル",
        image: "hotel04.jpg",
        provider_name: "ザ・リッツ・カールトン",
        time_zone: "昼",
        solo_level: "上級",
        likes_count: 45,
        favorites_count: 55,
    },
    {
        id: 23,
        subcategory: "シティホテル",
        image: "hotel05.jpg",
        provider_name: "アマン東京",
        time_zone: "夜",
        solo_level: "上級",
        likes_count: 50,
        favorites_count: 60,
    },
    {
        id: 24,
        subcategory: "シティホテル",
        image: "hotel06.jpg",
        provider_name: "フォーシーズンズ",
        time_zone: "朝",
        solo_level: "上級",
        likes_count: 48,
        favorites_count: 58,
    },
];